# Generated by Django 3.2.8 on 2021-11-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211107_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
